apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: kubeflow-artifact-storage
  namespace: kubeflow
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
EOF