apiVersion: serving.kubeflow.org/v1beta1
kind: InferenceService
metadata:
  name: fraud-detection
  namespace: kubeflow
spec:
  transformer:
    containers:
    - name: fraud-detection-transformer
      image: fraud-detection-transformer:latest
      resources:
        requests:
          cpu: "1"
          memory: "1Gi"
        limits:
          cpu: "2"
          memory: "2Gi"
      env:
      - name: MODEL_DIR
        value: "pvc://kubeflow-artifact-storage/fraud-detection/v1"
      - name: STORAGE_URI
        value: "pvc://kubeflow-artifact-storage/fraud-detection/v1"
  predictor:
    sklearn:
      storageUri: "pvc://kubeflow-artifact-storage/fraud-detection/v1"
      resources:
        requests:
          cpu: "1"
          memory: "2Gi"
        limits:
          cpu: "2"
          memory: "4Gi"